##部署使用
#server:
#  port: 6542
#
#spring:
#  application:
#    name: cloud-zuul-service
#
#eureka:
#  client:
#    #表示是否将自己注册进eurekaServer
#    register-with-eureka: true
#    #是否从eurekaServer提取已有的注册信息，默认为true,单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
#    fetch-registry: true
#    service-url:
#      defaultZone: http://114.116.249.36:7001/eureka/
##      ,http://eureka7002.com:7002/eureka/
##      defaultZone: http://localhost:7001/eureka
##  instance:
##    prefer-ip-address: true


#开发使用
server:
  port: 6542

spring:
  application:
    name: cloud-zuul-service

eureka:
  client:
    #表示是否将自己注册进eurekaServer
    register-with-eureka: true
    #是否从eurekaServer提取已有的注册信息，默认为true,单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
#      ,http://eureka7002.com:7002/eureka/
#      defaultZone: http://localhost:7001/eureka
#  instance:
#    prefer-ip-address: true